### ISSUE TITLE
How to override graph attributes?

### ISSUE THREAD

**Issue by JakeSummers** [mdaines/viz-js#104]
When I  run dot using the [Graphviz package](https://www.graphviz.org/download/), I can do the following: 

```
cat myFile.dot | dot -Grankdir=TB 
```

Is there a way that I can override graph attributes using this package?  I would prefer to avoid having to edit the files.  

Thanks!

**Comment by mdaines** [comment]
Currently no. This was originally to avoid having to pass a JavaScript array or object to a compiled C function, but it should be possible to do this using Emscripten's APIs for interacting with C code.
