### ISSUE TITLE
Question: How to compile library to webassembly

### ISSUE THREAD

**Issue by amilajack** [mdaines/viz-js#116]
I'm trying to mess around with this project and i'm wondering how I can enable wasm builds. I made the following changes:
https://github.com/amilajack/viz.js/commit/72d7ec65ceed32c40a88642cd5ae8f50f2cc971c#diff-b67911656ef5d18c4ae36cb6741b7965R40
https://github.com/amilajack/viz.js/commit/72d7ec65ceed32c40a88642cd5ae8f50f2cc971c#diff-b67911656ef5d18c4ae36cb6741b7965R32

And I'm running the builds with docker:
`docker exec -it emscripten make`

The build works with asm.js but it fails with wasm. Any ideas why this happens? Are there any other changes I need to make?

Here's the error:
```
Making install in webp
Making install in poppler
emcc --version | grep 1.37.33
emcc (Emscripten gcc/clang-like replacement) 1.37.33 ()
emcc -Oz --memory-init-file 0 -s WASM=1 -s USE_ZLIB=1 -s MODULARIZE=1 -s LEGACY_VM_SUPPORT=1 -s NO_DYNAMIC_EXECUTION=1 -s EXPORTED_FUNCTIONS="['_vizRenderFromString', '_vizCreateFile', '_vizLastErrorMessage', '_dtextract', '_Dtqueue']" -s EXPORTED_RUNTIME_METHODS="['Pointer_stringify', 'ccall', 'UTF8ToString']" -o build/module.js src/viz.c -I/src/prefix/include -I/src/prefix/include/graphviz -L/src/prefix/lib -L/src/prefix/lib/graphviz -lgvplugin_core -lgvplugin_dot_layout -lgvplugin_neato_layout -lcdt -lcgraph -lgvc -lgvpr -lpathplan -lexpat -lxdot
[wasm-validator error in function $_multilevel_spring_electrical_embedding_core] 4 != 1: call param types must match, on 
[none] (call $_remove_overlap
 [i32] (get_local $0)
 [i32] (get_local $12)
 [i32] (get_local $6)
 [i32] (get_local $5)
 [i32] (i32.load offset=124
  [i32] (get_local $3)
 )
...
```

**Comment by mdaines** [comment]
Simply adding `-s WASM=1` worked for me. However, I'm using Emscripten 1.37.36.

**Comment by amilajack** [comment]
Oh okay. Hmm. Can you please create a small example demonstrating this. Maybe I'm missing something. Could you push a branch out that shows the correct build config for wasm? I'm not experienced in makefiles or c/c++ build tools this this would really help me out. Thanks!

**Comment by mdaines** [comment]
My mistake. This only works for the lite version right now. I'm seeing a similar error for the full version.

I've pushed a branch with the WASM setting enabled: https://github.com/mdaines/viz.js/compare/wasm

To get the Wasm binary:

    make graphviz-lite build-lite/module.js

This will produce `build-lite/module.js` and `build-lite/module.wasm`.

**Comment by mdaines** [comment]
@amilajack I just pushed a change to both the master and wasm branches. Both targets should work now.

    make graphviz-lite build-lite/module.js
    make graphviz build/module.js

**Comment by mdaines** [comment]
Closing because v3 uses WebAssembly.
