### ISSUE TITLE
Method to get all available layout engines

### ISSUE THREAD

**Issue by nikeee** [mdaines/viz-js#142]
Is there any method that returns an array of all possible layout engines?

Currently, I'm copying the array in the docs:
https://github.com/mdaines/viz.js/wiki/API#render-options

However, I don't want to update this manually, as this can just be replaced by a single API call, if there was one. WOuld it be possible to add something like this?

**Comment by mdaines** [comment]
It might be. The `dot` program does something similar: it can generate a graph showing the available plug-ins, including layout engines. However, the list of layout engines in Viz.js is not likely to change very quickly.
