### ISSUE TITLE
multi-byte characters in labels take up twice as much space as in 'native' graphviz

### ISSUE THREAD

**Issue by sverweij** [mdaines/viz-js#147]
### Steps taken

Render this digraph with viz.js (either version 1.8.x or 2.0.0)

```dot
digraph {
  node [shape=box]
  "Hello world" [label="Привет мир"]
}
```
... or this one that uses html style label formatting...:

```dot
digraph {
  rankdir=LR
  node [shape=plaintext]
  "Hello world" [label= < 
    <table border="1" cellborder="0">
      <tr><td>Привет мир</td></tr>
    </table>
  >]
}
```

### Expected 
This is the output from the 'native' graphviz dot (version 2.40.1) respectively:
![regular-graphviz-output](https://user-images.githubusercontent.com/4822597/42329691-9d380db4-8071-11e8-9b7f-840690fe6e24.png) ![graphviz-output](https://user-images.githubusercontent.com/4822597/42329427-f4e9538e-8070-11e8-98ff-2557cb5bea36.png)

### Found
This is the viz.js output for both digraphs:
![regular-viz-js-output](https://user-images.githubusercontent.com/4822597/42329710-ab4b4cf4-8071-11e8-9ed5-1a4abfbbab69.png) ![viz-js-output](https://user-images.githubusercontent.com/4822597/42329442-fc342e8e-8070-11e8-8f45-106dd21a2caf.png)

**Comment by mdaines** [comment]
Closing because this appears to work in v3.
